export class BankDetailDTO {
  constructor(
    public id?: number,
    public version?: number,
    public customerId?: number,
    public bankAccountNum?: string,
    public ifscCode?: string,
    public micrCode?: string,
    public bankName?: string,
    public bankAccountType?: string,
    public accountHolderName?: string,
    public bankCode?: string,
    public bankBranch?: string,
    public bankAddress?: string,
    public bankContact?: string,
    public bankCity?: string,
    public bankDistrict?: string,
    public bankState?: string,
    public defaultBank?: boolean,
    public reviewStatus?: string,
    public rejectStatus?: boolean,
    public rejectReason?: string,
    public techIssueCheck?: boolean,
    public techIssueStatus?: boolean,
    public techIssueReason?: string,
    public reviewOptionList?: any,
    public reasonOptionsModel?: any,
    public techReviewOptionList?: any,
    public techReasonOptionsModel?: any,
    public accountVerificationStatus?: any,
    public accountVerificationDetailedStatus?: any,
    public accountHolderNameInBank?: string,
    public validateAccount?: boolean,
    public nachReviewStatus?: string
  ) {}
}
