import { BankDetailDTO } from "./bank-detail.model";

export class CustomerMutualFundSubscriptionsDTO {
    constructor(
        public id?: number,
        public version?: number,
        public customerSubscriptionsId?: number,
        public schemeCode?: string,
        public schemeName?: string,
        public percentage?: number,
        public productType?: string,
        public kycApplicationFormId?: string,
    ) {
    }
}

export class CustomerSubscription {
    constructor(
        public id?: number,
        public version?: number,
        public customerId?: number,
        public subscriptionDate?: any,
        public startDate?: any,
        public endDate?: any,
        public message1?: string,
        public message2?: string,
        public productNote?: string,
        public contributionAmount?: number,
        public finalContributionAmount?: number,
        public frequency?: string,
        public agreementId?: number,
        public status?: any,
        public schemes?: CustomerMutualFundSubscriptionsDTO[],
        public solution?: string,
        public contributionPeriod?: any,
        public accountNum?: string,
        public solutionCode?: string,
        public nextContributionDate?: any,
        public partnerId?: number,
        public customerName?: string,
        public enrollmentTemplateResponseHeaderId?: number,
        public algorithm_id?: string,
        public risk_level?: string,
        public paymentMode?: string,
        public nachMandateId?: number,
        public goal?: string,
        public goalAmount?: number,
        public computeContributionAmount?: boolean,
        public totalContribution?: number,
        public advisoryFee?: number,
        public liquidityCardEnrollmentFee?: number,
        public riskLevelText?: string,
        public riskDetailText?: string,
        public investedAmount?: any,
        public currentValue?: any,
        public nachStatus?: any,
        public nachVerificationStatus?: string,
        public nachStatusMessage?: string,
        public nachStatusCode?: string,
        public contributionPaymentCompleted?: number,
        public esignId?: number,
        public throwMessage?: string,
        public customErrorFlag?: boolean,
        public isPaperEsign?: boolean,
        public isDocumentCaptured?: boolean,
        public nachMode?: any,
        public contributionDisplayDate?: any,
        public nachReviewStatus?: any,
        public nachReviewAcceptedDate?: any,
        public nachReviewedBy?: string,
        public msaReviewStatus?: any,
        public msaReviewAcceptedDate?: any,
        public msaReviewedBy?: string,
        public kycReviewStatus?: any,
        public kycReviewAcceptedDate?: any,
        public kycReviewedBy?: string,
        public isResume?: boolean,
        public isRetry?: boolean,
        public activationDate?: any,
        public activationChannel?: string,
        public enrollmentDisplayDate?: any,
        public isWelcomeSmsSent?: boolean,
        public flowStage?: any,
        public createdDate?: any,
        public partnerName?: string,
        public lastUpdatedByUser?: string,
        public lastUpdatedByUserName?: string,
        public lastUpdatedByUserMobileNumber?: number,
        public bankDetailDTO?: BankDetailDTO,
        public subscriptionSubType?:string,
        public subscriptionType?:string,
        public supportedPaymentModes?: any
   ) {}
}
