
export const stubResponse = {
  "customerDTO": {
    "id": 135951,
    "version": 3,
    "name": "GokulRaj",
    "gender": "Male",
    "dateOfBirth": "1995-11-05",
    "fatherName": "Gokul",
    "motherName": null,
    "maritalStatus": "Single",
    "secondaryMobileNumber": null,
    "email": null,
    "address1": "11/163C8",
    "address2": "Periyar padipagam",
    "address3": null,
    "city": "MetturDam",
    "district": "MetturDam",
    "state": "Tamil Nadu",
    "country": "India",
    "aadhaarNumber": 123456789121,
    "aadhaarReferenceId": "5742b907-8d10-49f8-b408-a593dfcc6f87",
    "whatsAppConsent": null,
    "whatsAppNumber": null,
    "panNumber": "BKTPG5923R",
    "spouseName": "Pooja",
    "spouseDateOfBirth": null,
    "numberOfDependents": null,
    "nomineeName": null,
    "nomineeRelationship": null,
    "nomineeAddress": null,
    "status": null,
    "aadhaarEkyc": null,
    "aadhaarEsign": null,
    "esignTries": null,
    "creditBureauCheck": null,
    "personaScore": null,
    "longitude": null,
    "latitude": null,
    "pinCode": "636401",
    "errorCode": null,
    "enrollmentDate": null,
    "partnerCustomerId": "PC0002",
    "customerNumber": "135951",
    "bankAccountNum": null,
    "ifscCode": null,
    "micrCode": null,
    "bankName": null,
    "bankAccountType": null,
    "accountHolderName": null,
    "pekrnNumber": null,
    "partnerId": 12,
    "branchId": 44,
    "groupId": null,
    "nomineeDateOfBirth": null,
    "aadhaarFrontFileId": null,
    "aadhaarBackFileId": null,
    "panNumberFileId": null,
    "chequeFileId": null,
    "profilePhotoFileId": null,
    "signatureFileId": null,
    "ekycResponseCode": null,
    "ekycResponseMessage": null,
    "ekycDate": null,
    "customerCbCheckRequired": null,
    "partnerCbCheckRequired": null,
    "primaryMobileNumber": null,
    "profileCompleted": true,
    "kycApplicationFormId": null,
    "mobileNumberOwner": null,
    "debitCard": null,
    "debitCardBelongsTo": null,
    "bankCode": null,
    "bankBranch": null,
    "bankAddress": null,
    "bankContact": null,
    "bankCity": null,
    "bankDistrict": null,
    "bankState": null,
    "kycType": null,
    "enrolmentFeePaid": false,
    "enrollmentMode": null,
    "profile": "{\"Sourcing details\":{\"Channel\":\"Branch\"},\"Financial details of applicant for Year 1\":{\"Net worth\":\"2000\",\"Net profit after tax\":\"300\",\"Net sales\":\"1000\",\"Operating profit\":\"500\"},\"Associate Entity\":{\"ID Proof no\":\"1123\",\"Net worth\":\"2000000\",\"ID Proof type\":\"GST\",\"Nature of business\":\"Product\",\"Net sales\":\"1000000\",\"Name of entity\":\"Buz-fintech\",\"Net profit\":\"100000\"},\"Financial details of applicant for Year 3\":{\"Net worth\":\"6000\",\"Net profit after tax\":\"900\",\"Net sales\":\"3000\",\"Operating profit\":\"1500\"},\"Financial details of applicant for Year 2\":{\"Net worth\":\"4000\",\"Net profit after tax\":\"600\",\"Net sales\":\"2000\",\"Operating profit\":\"1000\"},\"Coverage under PMSBY/ PMJJBY/ APY\":\"APY\",\"Trade Reference 1\":{\"Contact Person details\":\"TR2\",\"Address\":\"TR4\",\"Contact no\":\"TR5\",\"Name of entity\":\"TR1\",\"Direct Agri, Jhadi & Village industries  etc\":\"Agri\",\"Relationship with\":\"TR3\"},\"Land Holding\":\"Yes\",\"Trade Reference 2\":{\"Contact Person details\":\"TR2 contact\",\"Address\":\"HSR Layout, Bangalore\",\"Contact no\":\"6362874994\",\"Name of entity\":\"TR REF2\",\"Direct Agri, Jhadi & Village industries  etc\":\"Jhadi\",\"Relationship with\":\"TR2 Father\"},\"Profession\":\"Software Enigneer\",\"Family Assets\":{\"Jewellery\":\"7\",\"Others\":\"0\",\"Lands\":\"4\",\"Residential\":\"9\",\"Factory Premise\":\"5\",\"Livestock\":\"1\",\"House\":\"6\",\"Agrl. Implements\":\"2\",\"Vehicles\":\"3\"},\"House Type\":\"Building\",\"Educational Qualification\":\"BE-MECH\",\"Project Funding Details\":{\"Own funds\":\"1Cr\",\"LTV %\":\"80%(~1Cr)\",\"Total\":\"6Cr\",\"PSL Classification\":\"SC\",\"Loan (Bank fund)\":\"4Cr\"},\"Caste\":\"MBC\",\"Business\":{\"Annual Surplus  (Household and Business) (INR)\":\"30\",\"Description of business\":\"IT\",\"Business vintage\":\"2\",\"Industry Type\":\"Finance\",\"Source of income\":\"IT\",\"Business Pan No\":\"BICPS2566J\",\"Business GST No\":\"12345678\",\"Annual Income (Household and Business) (INR)\":\"10\",\"Annual Expenditure (Household and Business) (INR)\":\"20\",\"Name of enterprise\":\"My ent\"}}",
    // "profile": '{"Family Assets":"","Land Holding":"No","Profession":"Barber","House Type":"RoofTop","Educational Qualification":"12","Caste":"Nil","Coverage under PMSBY/ PMJJBY/ APY":"Yes"}',
    "centerId": 14946,
    "reviewStatus": null,
    "rejectReason": null,
    "kycOnboardingStatus": null,
    "highmarkStatus": null,
    "customerDisplayName": null,
    "isTestCustomer": null,
    "customerState": null,
    "poiDocType": null,
    "poaDocType": null,
    "kycReviewStatus": null,
    "kycReviewAcceptedDate": null,
    "kycReviewedBy": null,
    "merchantId": null,
    "techIssueStatus": null,
    "techIssueReason": null,
    "preferredContactTime": null,
    "rejectedAccountCount": 0,
    "accountVerificationStatus": null,
    "accountVerificationDetailedStatus": null,
    "subscriptionCount": null,
    "kycState": null,
    "language": null,
    "pepStatus": null,
    "emailVerified": false,
    "occupationType": null
  },
  "kycDetailsList": [
    {
      "id": 205502,
      "version": 1,
      "customerId": 135951,
      "providerId": 135951,
      "providerName": "KALEIDOFIN",
      "purpose": "POI",
      "verificationStatus": "Pending",
      "message": null,
      "idNo": null,
      "documentType": "Aadhaar_front",
      "customerFileMappingId": 317862,
      "sortOrder": null,
      "expiryDate": null,
      "groupId": "5b9fa661-19dc-44b7-af65-2609ab5f4b72",
      "default": null
    },
    {
      "id": 205503,
      "version": 1,
      "customerId": 135951,
      "providerId": 135951,
      "providerName": "KALEIDOFIN",
      "purpose": "POI",
      "verificationStatus": "Pending",
      "message": null,
      "idNo": null,
      "documentType": "Aadhaar_back",
      "customerFileMappingId": 317863,
      "sortOrder": null,
      "expiryDate": null,
      "groupId": "5b9fa661-19dc-44b7-af65-2609ab5f4b72",
      "default": null
    }
  ],
  "customerFileMappingDTOList": [
    {
      "id": 317862,
      "customerId": 135951,
      "fileType": "Aadhaar_front",
      "fileId": 1094753,
      "reviewStatus": "PENDING",
      "rejectReason": null,
      "origFileMappingId": null,
      "techIssueStatus": null,
      "techIssueReason": null,
      "uploadedDate": "2021-11-26T14:30:30",
      "expiryDate": null
    },
    {
      "id": 317863,
      "customerId": 135951,
      "fileType": "Aadhaar_back",
      "fileId": 1094754,
      "reviewStatus": "PENDING",
      "rejectReason": null,
      "origFileMappingId": null,
      "techIssueStatus": null,
      "techIssueReason": null,
      "uploadedDate": "2021-11-26T14:30:30",
      "expiryDate": null
    }
  ],
  "nomineeDetails": {
    "id": 29127,
    "version": 0,
    "name": "Senthamarai",
    "dateOfBirth": "1970-12-12",
    "nomineeRelationship": "Mother",
    "address1": "11/163c8",
    "address2": null,
    "city": null,
    "state": null,
    "pincode": null,
    "customerId": 135951,
    "addressId": 79,
    "guardianNomineeRelationship": null,
    "guardianAddressId": null,
    "minor": true,
    "default": false,
    "guardianDOB": "2022-01-08",
    "guardianName": "new guardian"
  },
  "bankDetail": {
    "id": 37391,
    "version": 0,
    "customerId": 135951,
    "bankAccountNum": "51234567890",
    "ifscCode": "SBIN0000877",
    "micrCode": null,
    "bankName": "SBI",
    "bankAccountType": "Savings",
    "accountHolderName": "GokulRaj",
    "bankCode": null,
    "bankBranch": "Mettur",
    "bankAddress": null,
    "bankContact": null,
    "bankCity": null,
    "bankDistrict": null,
    "bankState": null,
    "defaultBank": null,
    "reviewStatus": null,
    "rejectReason": null,
    "techIssueStatus": null,
    "techIssueReason": null,
    "fileMappingId": null,
    "validateAccount": false,
    "accountVerificationStatus": null,
    "isNachModeOffline": false,
    "provider": null,
    "providerResponseCode": null,
    "providerDescription": null,
    "accountVerificationDetailedStatus": null,
    "accountHolderNameInBank": null,
    "rejectedAccountCount": 0,
    "nachReviewStatus": null
  },
  "existingLoansDTOList": [
    {
      "id": 76,
      "version": 1,
      "customerId": 123,
      "loanType": "Loan",
      "instituteName": "samasta",
      "accountNumber": "3213",
      "loanAmount": 1233,
      "tenure": 12,
      "emiAmount": 1233,
      "outstandingAmount": 432432,
      "loanApplicationNumber": 32321
    }
  ],
      "addressDTOList": [
    {
      "id": 76,
      "version": 0,
      "customerId": 135951,
      "addressType": "CURRENT",
      "address1": "11/163C8",
      "address2": "Periyar padipagam",
      "address3": null,
      "city": "MetturDam",
      "district": "MetturDam",
      "state": "Tamil Nadu",
      "country": "India",
      "pincode": 636401
    },
    {
      "id": 77,
      "version": 0,
      "customerId": 135951,
      "addressType": "PERMANENT",
      "address1": "11/163C8",
      "address2": "Periyar padipagam",
      "address3": null,
      "city": "MetturDam",
      "district": "MetturDam",
      "state": "Tamil Nadu",
      "country": "India",
      "pincode": 636401
    },
    {
      "id": 78,
      "version": 0,
      "customerId": 135951,
      "addressType": "BUSINESS",
      "address1": "11/163C8",
      "address2": "Periyar padipagam",
      "address3": null,
      "city": "MetturDam",
      "district": "MetturDam",
      "state": "Tamil Nadu",
      "country": "India",
      "pincode": 636401
    },
    {
      "id": 79,
      "version": 0,
      "customerId": 135951,
      "addressType": "NOMINEE",
      "address1": "11/163c8",
      "address2": null,
      "address3": null,
      "city": null,
      "district": null,
      "state": null,
      "country": null,
      "pincode": null
    }
  ],
  "partnerDTO": {
    "id": 12,
    "version": 13,
    "name": "Samasta Micro Finance",
    "code": "p0012",
    "typeOfPartner": "1",
    "isPartnerCustomerIdMandatory": false,
    "cashCollectionMode": "Deferred",
    "computeContributionAmount": false,
    "owner": false,
    "cbCheckRequired": false,
    "defaultResponse": "{\"responses\":[{\"solution\":\"LAKSHYA\",\"contributionAmount\":1000,\"contributionPeriod\":24,\"frequency\":\"MONTHLY\",\"ekycRequired\":\"TRUE\",\"algorithm_id\":\"defalt\",\"message1\":\"Lakshyaworksbestforshort/meddurationgoals.Ifyoucontinuetomakeyourcontributionsontime,weensurethatyouachieveyourtargetedgoalamountsuccessfully\",\"message2\":\"Itcombinesthepowerofsaving/investments\",\"productNote\":\"Yourcontributionsareinvestedin:MutualFunds\",\"solutionCode\":\"L\",\"schemes\":[{\"schemeCode\":\"1543\",\"schemeName\":\"ICICI Prudential Floating Interest Fund - Growth\",\"percentage\":100,\"productType\":\"MF\"}]}]}",
    "minFirstContributionAmountRequired": false,
    "minFirstContributionAmount": 500,
    "firstAdminFeeInclusive": false,
    "recurringAdminFeeInclusive": false,
    "customerPaymentMode": "NACH",
    "payDate": 1,
    "paymentDate1": null,
    "paymentDate2": null,
    "helplineNumber": "900000001",
    "contributionAmountMultiplesOf": 100,
    "paymentDates": "7,21",
    "skipCycle": "FULL",
    "futureCollectionsRange": 30,
    "minGoalAmount": null,
    "minGoalTenure": null,
    "partnerStatus": null,
    "maxNoOfInvitations": null,
    "invitationExpiryDays": null,
    "subDomain": "samasta",
    "fileId": null,
    "signzyConfiguration": 1,
    "namePartnerCustomerId": "NAME",
    "invitationFrequency": null,
    "lastInvitationSentDate": null,
    "schemeCode": null,
    "uiFlowConfiguration": "{\n  \"enrollment_flow\": 2,\n  \"disable_add_customer\": 0,\n  \"retry\": 2,\n  \"resume\": 2,\n  \"edit_profile\": 2,\n  \"features\": [\n    {\n      \"loan_payment\": {\n        \"enabled\": true,\n        \"sub_type\": \"DIGINACH\",\n        \"penny_drop_enabled\": false,\n        \"nach_configuration\": {\n\"capture_nach_max_amount\": true,\n\"capture_nach_start_date\": false,\n\"capture_nach_end_date\": false,\n\"nach_accuracy_guide_images\":\"1,2,3,4,5\",\n\"minimum_gap_between_start_date_end_date_in_months\": 0,\n\"min_nach_max_amount\":5000,\n\"max_nach_max_amount\":200000\n}\n      },\n      \"kaleidofin_goal\": {\n        \"enabled\": true,\n        \"penny_drop_enabled\": true,\n\t\t\"nach_configuration\": {\n\t\t\t\"nach_accuracy_guide_images\":\"1,2,3,4,5\",\n            \"capture_nach_max_amount\": true,\n\t\t\t\"min_nach_max_amount\":5000,\n\t\t\t\"max_nach_max_amount\":200000\n\t\t}\n      },\n      \"reset_password\": {\n        \"mandatory\": true\n      }\n    }\n  ]\n}",
    "enrollmentFeeByPercentage": 0,
    "isPartnerSpecificAdvisoryFee": false,
    "maxGoalTenure": 18,
    "maxContributionAmount": 100000000,
    "autoReviewConfiguration": "{\"KF_GOAL\": {\"KYC\": false, \"NACH\": false, \"MSA\": false}, \"PARTNER_LOAN\": {\"KYC\": false, \"NACH\": false, \"MSA\": false}}",
    "nachMaxAmountForDiginach": 5000,
    "nachMaxAmountForGoals": 5000,
    "minLumpSumGoalAmount": null,
    "typeOfMsaTemplate": "kaleidopayKannada",
    "numberOfNachForms": 2,
    "lastModifiedDate": "2021-11-29T10:22:41Z"
  },
  "branchDTO": {
    "id": 44,
    "version": 1865,
    "name": "Testsamata",
    "code": "Testsamata",
    "currentWorkingDate": null,
    "branchOpenDate": null,
    "weekendDay1": null,
    "weekendDay2": null,
    "operationalStatus": null,
    "address1": null,
    "address2": null,
    "address3": null,
    "country": null,
    "state": null,
    "city": "Chennai",
    "district": null,
    "pincode": null,
    "partnerId": 12,
    "location1Id": null,
    "location1Name": "l1207",
    "location2Id": null,
    "location2Name": null,
    "location3Id": null,
    "location3Name": null,
    "location4Id": null,
    "location4Name": null,
    "location5Id": null,
    "location5Name": null
  },
  "centerDTO": {
    "id": 14946,
    "version": 0,
    "name": "TestEX1000",
    "code": "1000",
    "branchId": 44,
    "partnerId": 12
  },
  "loanApplicationDTO": {
    "id": 445,
    "version": 13,
    "lendingPartnerCode": null,
    "loanTenure": 60,
    "customerNumber": "135951",
    "applicationNumber": "5654368545074137825",
    "applicationDate": "2021-11-26",
    "accountNumber": null,
    "purpose": "House Renovation",
    "loanAmount": 300000,
    "loanAmountSanctioned": null,
    "loanAmountDisbursed": null,
    "disbursementDate": null,
    "status": 1,
    "productCode": "T402",
    "sanctionedDate": null,
    "lienMarkedDate": null,
    "openedDate": null,
    "customerSubscriptionNumber": null,
    "partnerSchemeId": null,
    "partnerLoginId": null,
    "partnerLoanId": "M00000002",
    "loanType": "Entrepreneural",
    "customerName": null,
    "loanApplicationStatusKey": null,
    "loanUpdateState": null,
    "secondaryMobileNumber": null,
    "techIssue": null,
    "normalInterestRate": null,
    "dueDay": null,
    "nachMandateStatus": null,
    "loanClosedDate": null,
    "emiStartDate": null,
    "nextEmiDate": null,
    "monthlyEmi": null,
    "pendingEmi": null,
    "paymentStatus": null,
    "paymentType": null,
    "numDemands": null,
    "nachMandateConsumerId": null,
    "solutionCode": null,
    "eligibilityPercent": null,
    "channelPartnerCode": "p0012",
    "outstandingLoanAmount": null,
    "agreementConsent": null,
    "acceptanceDate": null,
    "documentId": null,
    "existingDemands": null,
    "futureDemands": null,
    "emiDate": null,
    "emiAmount": null,
    "outstandingBalance": null,
    "totalRepaid": null,
    "numSatisifiedDemands": null,
    "penalInterestDue": null,
    "feeDue": null,
    "eligibleAmount": null,
    "lienReleaseDate": null,
    "lienConsent": null,
    "lienAcceptanceDate": null,
    "lienMarkingStatus": null,
    "disbursementStatus": null,
    "accountStatement": null,
    "lienHoldings": null,
    "isEmandate": null,
    "subsectorCode": 632,
    "applicationStatus": "pending",
    "kiscore": 8,
    "eligibility": true,
    "eligibilityResult": "[{\"eligibilityRule\":\"JLG_GROUP_SIZE\",\"result\":\"PASS\",\"comment\":\"Group size <5> is greater than min group size <1>\"},{\"eligibilityRule\":\"LOAN_AMOUNT\",\"result\":\"FAIL\",\"comment\":\"Loan amount <Rs. 40000.00> is greater than max loan amount <10000.00>\"},{\"eligibilityRule\":\"LOAN_TENURE\",\"result\":\"FAIL\",\"comment\":\"Loan tenure <12 months> is less than min loan tenure <60> for loan amount greater than 3000.00\"},{\"eligibilityRule\":\"KISCORE\",\"result\":\"PASS\",\"comment\":\"Kiscore <6> is greater than min Kiscore <5>\"}]",
    "kycGroupId": "5b9fa661-19dc-44b7-af65-2609ab5f4b72",
    "bankDetailId": 37391,
    "nomineeId": 29127,
    "agreementSigned": true,
    "remarks": "CR",
    "partnerId": 12,
    "partnerCustomerId": "PC0002",
    "groupId": null,
    "loanApplicationDocumentDTOs": null,
    "loanObligatorDTOs": null,
    "nextDueDate": null,
    "requiredDataProvided": true,
    "kycCompleted": null,
    "firstTimeLoan": null
  },
  "loanApplicationDocumentDTOList": [
    {
      "id": 271,
      "version": 1,
      "documentName": "Application",
      "documentType": "Application",
      "loanApplicationId": 445,
      "documentFileId": 1094756,
      "reviewStatus": "Pending",
      "reviewRemarks": null
    },
    {
      "id": 272,
      "version": 1,
      "documentName": "Agreement",
      "documentType": null,
      "loanApplicationId": 445,
      "documentFileId": 1094784,
      "reviewStatus": "Pending",
      "reviewRemarks": null
    },
    {
      "id": 273,
      "version": 1,
      "documentName": "supporting_document",
      "documentType": "SupportingDocument",
      "loanApplicationId": 445,
      "documentFileId": 1094757,
      "reviewStatus": "Pending",
      "reviewRemarks": "12_mark_sheet"
    },
    {
      "id": 282,
      "version": 1,
      "documentName": "supporting_document",
      "documentType": "SupportingDocument",
      "loanApplicationId": 445,
      "documentFileId": 1094783,
      "reviewStatus": "Pending",
      "reviewRemarks": "CR"
    }
  ],
  "loanObligatorDTOList":[
     {
        "id":52,
        "version":0,
        "loanApplicationId":439,
        "name":"dinesh",
        "relationship":"brother",
        "mobileNo":null,
        "dateOfBirth":null,
        "addressDTO":null,
        "remarks":null,
        "type":"GUARANTOR"
     },
    {
      "id":56,
      "version":0,
      "loanApplicationId":439,
      "name":"ganesh",
      "relationship":"brother",
      "mobileNo":null,
      "dateOfBirth":null,
      "addressDTO":null,
      "remarks":null,
      "type":"GUARANTOR"
    },
     {
        "id":53,
        "version":0,
        "loanApplicationId":439,
        "name":"Krish",
        "relationship":null,
        "mobileNo":null,
        "dateOfBirth":null,
        "addressDTO":null,
        "remarks":"Good",
        "type":"REFERENCE"
     },
     {
        "id":54,
        "version":0,
        "loanApplicationId":439,
        "name":"Babar",
        "relationship":null,
        "mobileNo":null,
        "dateOfBirth":null,
        "addressDTO":null,
        "remarks":"Good",
        "type":"REFERENCE"
     }
  ],
  "familyDetailsList":[
    {
        "id": 5,
        "version": 0,
        "customerId": 136421,
        "relationName": "Sindhuja",
        "relationship": "Sister",
        "gender": "Female",
        "dob": "1991-12-20",
        "occupation": "Teacher",
        "educationalStatus": "Bed",
        "mobileNumber": null,
        "customer": null
    },
    {
        "id": 6,
        "version": 0,
        "customerId": 136421,
        "relationName": "Akila",
        "relationship": "Sister",
        "gender": "Female",
        "dob": "1996-12-20",
        "occupation": "House Wife",
        "educationalStatus": "Bed",
        "mobileNumber": null,
        "customer": null
    },
    {
        "id": 7,
        "version": 0,
        "customerId": 136421,
        "relationName": "Durairaj",
        "relationship": "Father",
        "gender": "Male",
        "dob": "1952-12-20",
        "occupation": "Barber",
        "educationalStatus": "10",
        "mobileNumber": null,
        "customer": null
    },
    {
        "id": 8,
        "version": 0,
        "customerId": 136421,
        "relationName": "Senthamarai",
        "relationship": "Mother",
        "gender": "Female",
        "dob": "1971-12-20",
        "occupation": "HouseWife",
        "educationalStatus": "10",
        "mobileNumber": null,
        "customer": null
    }
]
};
